#pragma once
// Generated by bin/generate_windows_native_files.js
// DO NOT EDIT - This file is auto-generated
//
// TurboModules (9) will be auto-registered by AddAttributedModules()
// Fabric Components (2) require manual registration calls


#include "../../app/native/IRActionMenuManager/IRActionMenuManager.windows.h"
#include "../../app/native/IRClipboard/IRClipboard.windows.h"
#include "../../app/native/IRFontList/IRFontList.windows.h"
#include "../../app/native/IRKeyboard/IRKeyboard.windows.h"
#include "../../app/native/IRPassthroughView/IRPassthroughView.windows.h"
#include "../../app/native/IRRunShellCommand/IRRunShellCommand.windows.h"
#include "../../app/native/IRSystemInfo/IRSystemInfo.windows.h"
#include "../../app/native/IRSystemMenuManager/IRSystemMenuManager.windows.h"
#include "../../app/native/IRTabComponentView/IRTabComponentView.windows.h"
#include "../../app/utils/experimental/IRExperimental.windows.h"
#include "../../app/utils/random/IRRandom.windows.h"

namespace winrt::reactotron::implementation {
    // Fabric component registration functions
    void RegisterIRPassthroughNativeComponent(winrt::Microsoft::ReactNative::IReactPackageBuilder const& packageBuilder) noexcept;
    void RegisterIRTabNativeComponent(winrt::Microsoft::ReactNative::IReactPackageBuilder const& packageBuilder) noexcept;
    
    // Helper function to register all Fabric components
    void RegisterAllFabricComponents(winrt::Microsoft::ReactNative::IReactPackageBuilder const& packageBuilder) noexcept;
}
