require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# React Native Colo Loco autolinks native files colocated next to your JS files
# More info here: https://github.com/jamonholmgren/react-native-colo-loco
# In this case, we've included the linker.rb file in the bin folder so we
# don't have to have another npm dependency.
require_relative "../bin/linker.rb"
link_colocated_native_files(
  app_name: 'Reactotron-macOS',
  app_path: "#{Pod::Config.instance.installation_root}/../app",
  xcodeproj_path: "#{Pod::Config.instance.installation_root}/Reactotron.xcodeproj",
  exclude_targets: [],
  clean: !ENV['COLO_LOCO_CLEAN'].nil?
)

prepare_react_native_project!

target 'Reactotron-macOS' do
  platform :macos, '11.0'
  use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
