require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# React Native Colo Loco for CocoaPods - generates files for our local pod
# This is based on the original bin/linker.rb file, but modified to generate files for our local pod
# See https://github.com/jamonholmgren/react-native-colo-loco for more details

require_relative "../bin/generate_native_files.rb"
generate_native_files_for_pod(
  app_path: "#{Pod::Config.instance.installation_root}/../app",
  project_root: "#{Pod::Config.instance.installation_root}/..",
  clean: !ENV['COLO_LOCO_CLEAN'].nil?
)

prepare_react_native_project!

target 'Reactotron-macOS' do
  platform :macos, '11.0'
  use_native_modules!

  # Local pod for all our native modules
  pod 'IRNativeModules', :path => '..'

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
